config/routes.rb
Rails.application.routes.draw do
  get 'users' => 'users#index'
 # get 'users/show' => 'users#show'
  get 'users/new' => 'users#new'
  post 'users' => 'users#create'
  post 'users/edit'
  post 'users/update'
  delete 'users/destroy'
  get 'users/:id' => 'users#show', as: :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  has_many :phones
  validates :name, presence: true, uniqueness: { case_sensitive: false, scope: :user_id, message: 'Only different contacts name allowed for same user' }
  validates :birthdate_before_type_cast, format: { with: %r/(0?[1-9]|[12][0-9]|3[01])[\/\-](0?[1-9]|1[012])[\/\-]\d{4}/ }, allow_blank: true
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :contact
  validates :number, presence: true, uniqueness: { scope: :contact_id }
  validates :kind, presence: true
  validates :primary, :inclusion => { :in => [true, false] }
  validates :primary, uniqueness: { scope: :contact_id }, if: :primary

  before_save :disable_previous_primary, if: :primary

  def check_if_primary_true
    phones = Phone.all
    phones.each do |phone|
      if phone['primary'] == true
        phone.update_attribute(:primary, false)
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :contacts
  has_many :phones, through: :contacts
  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.includes(:contacts, :phones)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit

  end

  def update
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :age, :bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    <title>UserRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div class="container">
  <table class="table">
    <caption class="table__caption">User</caption>
    <thead>
      <tr class="table__head">
        <th>Name</th>
        <th>Age</th>
        <th>Bio</th>
        <th>Contacts</th>
        <th>Phones</th>
        <th></th>
      </tr>
    </thead>
    
    <tbody class="table__body">
    <% @users.each do |user| %>
      <tr>
        <th><%= user.name %></th>
        <th><%= user.age %></th>
        <th><%= user.bio %></th>
        <th><%= user.contacts.length %></th>
        <th><%= user.phones.length %></th>
        <th><%= link_to 'Show', user, class: 'button__show' %></th>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<div class="container">
  <div class="button">
    <%= link_to 'New User', users_new_path %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h2>New User</h2>
</div>
<div class="container">
  <div class="form">
    <%= form_with model: @user do |form| %>
    <div class="form__input">
      <div class="form__label">
        <%= form.label :name %>
      </div>
      <div>
        <%= form.text_field :name, class: 'form__text' %>
      </div>
      <div>
        <% @user.errors.full_messages_for(:name).each do |message| %>
        <div class="form__error"><%= message %></div>
        <% end %>
      </div>
    </div>
  
    <div class="form__input">
      <div class="form__label">
        <%= form.label :age %>
      </div>
      <div>
        <%= form.number_field :age, in: 1..150, class: 'form__text' %>
      </div>
    </div>
    <div class="form__input">
      <div>
        <div class="form__label">
          <%= form.label :bio %>
        </div>
        <div>
          <%= form.text_area :bio, class: 'form__text'%>
        </div>
      </div>
    </div>
      
    <div class="form__submit">
      <%= form.submit class: 'button' %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <table class="table">
    <tr>
      <th class="table__head table__body">Name</th>
      <th class="table__body"><%= @user.name %></th>
    </tr>
    <tr>
      <th class="table__head table__body">Age</th>
      <th class="table__body"><%= @user.age %></th>
    </tr>
    <tr>
      <th class="table__head table__body">Bio</th>
      <th class="table__body"><%= @user.bio %></th>
    </tr>
  </table>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>